synergistic-silobusters/flintandsteel

server/server.js
src/ideas/ideasView/ideasView.js
src/navigation/sidenav.js

This was an experiment to simulate realtime data for the sidenav and for the ideaView. It turned out pretty nicely. Any new idea that is created shows up on all sessions near instantaneously. Any new likes, comments, and backs also show up in the idea view. Now if only I could animate them :stuck_out_tongue_closed_eyes:

Experiment real time experience

---

server/idea.js
server/ideas.js
server/server.js
src/ideas/ideasView/ideasView.js
src/navigation/sidenav.js

Server Sent Events replace the intervals. If any new idea is added or an idea is liked, the sidenav will change for all clients. If you are browsing a particular idea and it gets liked, commented, or backed, you will see that data update on your screen.

Realtime data

---

bower.json
package.json
server/server.js
src/app.js
src/ideas/ideasView/ideasView.js
src/ideas/ideasView/ideasView.spec.js
src/ideas/ideasView/ideasView.tpl.html
src/users/loginView/loginView.js

Issue #58, #66
Server Sent Events were throwing console errors.
Small bug with auto-redirect on login
Temporary fix for #59, but we still need angular-material to fix autocomplete for good via the other issues.

Issues #58, #66, and clean up

---

bower.json
src/ideas/ideasView/ideasView.js
src/ideas/ideasView/ideasView.tpl.html
src/index.html
src/users/loginView/loginView.tpl.html

This makes IE a little more usable. You can login and see ideas. There's still some work to be done.
Comment and Back tabs are still not visible on idea pages.
Front page still has all the content squished together.

IE fix attempts

---

bower.json
src/homeView/homeView.tpl.html
src/users/signupView/signupView.tpl.html

Issue 46: Resolves IE Incompatibilities

---

CONTRIBUTING.md
README.md

Contributing to flintandsteel in style! Refers to issue #79!
Reviewers requested: @Mctalian @bcbrennecke @davethenipper @LongArmMcGee

Added a CONTRIBUTING.md

---

.travis.yml

We're going to have to add the little travis CI status indicator once this is on master. 
This will run tests every time anything is committed to the repo through commits and through PRs, this way we can make sure code coming in is actually good!
Requested reviewers - @Mctalian @davethenipper

Travis-CI integration!

---

server/ideas.js
server/server.js
src/ideas/ideaSvc/ideaSvc.js
src/ideas/ideaSvc/ideaSvc.mock.js
src/ideas/ideaSvc/ideaSvc.spec.js
src/ideas/ideasView/ideasView.js
src/ideas/ideasView/ideasView.spec.js
src/ideas/ideasView/ideasView.tpl.html
src/index.html
src/users/loginView/loginView.js

These commits complete the idea deletion story.
Requested reviewers: @davethenipper, @YashdalfTheGray

Deleting ideas

---

src/index.html

Sidenav will sort by number of likes (for now) and will only show top 5 ideas. This will allow Braun's new page to be a link on the side nav so people can see all the ideas, not just the "top" ideas.
Not a story, but something I've wanted to do for a while.
Requested Reviewers: @YashdalfTheGray , @bcbrennecke

Sort by likes

---

server/ideas.js
src/homeView/homeView.tpl.html
src/ideas/ideaBrowseView/ideaBrowseView.tpl.html
src/ideas/ideaItemBrowse/ideaItemBrowse.tpl.html
src/index.html

Not compatible for IE.  We will work on that.  Approve me!  @Mctalian @YashdalfTheGray

Idea browse page

---

src/ideas/ideasView/ideasView.js
src/ideas/ideasView/ideasView.spec.js
src/ideas/ideasView/ideasView.tpl.html

My first pull request.  Let me know how it goes.
This delivery contains all the team changes.
@YashdalfTheGray @Mctalian

Team changes delivery

---

server/server.js

Password was not being decoded and the fake credentials weren't short enough for us complainers.
@LongArmMcGee @bcbrennecke

Fix dev login

---

src/assets/app.css
src/index.html

Added an All  Ideas button in top left. Made the Ideas icon available on
the home page for consistency.
FIRST PR!
ERMAGERD

'All Ideas' Navigation

---

gulpfile.js

Closes #126 
@YashdalfTheGray @LongArmMcGee

Fix nodemon

---

server/server.js
src/ideas/ideasView/ideasView.js

Apparently in all of my tests, I never mistyped the credentials :wolf:

Fixes invalid login crash

---

src/index.html
src/navigation/toolbar.js
src/users/accountView/accountView.js
src/users/accountView/accountView.tpl.html

@YashdalfTheGray @Mctalian @LongArmMcGee

Added menu drop down when logged in for profile navigation or logout

---

gulpfile.js
package.json
src/assets/app.css
src/index.html

Production was blocking the request for the Open Sans font because it was over HTTP not HTTPS. Made that small change.
Also, the reordering of the damn index.html injections was pissing me off, so here's hoping that's finally fixed.
One last thing, I specified commits for projects in the package.json that didn't have Releases or Tags. To make sure they don't update their package and break OUR stuff.

HTTPS for Open Sans, Ordering Inject index.html, Specifying commits

---

src/index.html
src/navigation/toolbar.js
src/toastSvc/toastSvc.js
src/users/accountView/accountView.js
src/users/accountView/accountView.tpl.html

Also changed the sizes a bit to make them more centered to their white background.
Cleaned up a console error when refreshing on the Account Page.
Fixed a weird JSCS error where it complained about a space at the end of a line.

Identicons on Toolbar were different from on Account Page

---

.travis.yml
gulpfile.js

Added a gulp command to run jshint and jscs on the code called `gulp code-check`. 
I also uncommented the gulp usage documentation for `generate:data`. 
Reviewers requested: @Mctalian @bcbrennecke @davethenipper

added a code check shortcut

---

README.md
generateData.js
gulpfile.js
server/db.js
server/ideas/ideas.js
server/routes.js
server/server.js
src/toastSvc/toastSvc.js
src/users/accountView/accountView.js

This might not be a completely finished thing, but it's a start and I have a decent amount in here I'd like looked over. A lot of commented out code that I want to keep in here for discussion and add or remove based on those discussions.
Some load testing results (on my beast home rig, so we're going to compare just based on this machine, not actual production) (times are in ms, we're creating a bunch of ideas, which I assume is our most expensive operation):
```
// Creating 1000 ideas with up to 100 concurrent connections =========================
With Prints:
stats:  { 
totalElapsed: 77959.77049300075,
main: { 
meter: { 
mean: 12.829416280310951,
count: 1000,
currentRate: 12.829402746257264,
'1MinuteRate': 9.224287414972048,
'5MinuteRate': 2.692730345952206,
'15MinuteRate': …
```

Load Testing

---

src/ideas/ideaItemBrowse/ideaItemBrowse.tpl.html

closes Issue #146. checks for number of team members and uses the the correct form of 'person' on the ideaitembrowse card

pluralize idea browse 'person'

---

src/assets/app.css
src/ideas/ideaBrowseView/ideaBrowseView.tpl.html
src/index.html

Simply added a message on the side nav and ideas browse view when no ideas exist. Not sure if the message "No ideas" is too brief or not, let me know.
Here are some screenshots:
@YashdalfTheGray  @Mctalian @davethenipper @LongArmMcGee @bcbrennecke @alanlgirard @monotkate

Added 'No Ideas' message on side nav and browse view

---

src/assets/app.css
src/ideas/ideaBack/ideaAddBack.tpl.html
src/ideas/ideaBack/ideaEditBack.tpl.html
src/ideas/ideaItem/ideaItem.tpl.html
src/ideas/ideasView/ideasView.js
src/ideas/ideasView/ideasView.tpl.html
src/index.html

Added Tooltips.  Opening for discussion some of the wording and appearance.  I worded backing tooltips as contributions to potentially get people used to the term back, but can change it easily.  
Backing now triggers a dialog window.  This window can be triggered from either the little person icon next to the like (feel free to suggest a different icon), or from the backers window with the button.  If you have already created a back, the little person will trigger an edit instead of an add (tooltip updates as appropriate).  You can also edit from the backers page by clicking on the edit next to your back.  Which I just realized could use a tooltip.  If the window is clicked off in the middle of an edit, it will not submit the edit.  
This is going to fail one of the syntax tests because …

Tooltips and Backing Dialog

---

src/ideas/ideasView/ideasView.tpl.html

Closes #194, see commit comments or issue discussion for a bit more info.

Fixes botched merge from a LONG time ago

---

src/assets/app.css
src/assets/ic_email_black_24px.svg
src/ideas/ideasView/ideasView.js
src/ideas/ideasView/ideasView.tpl.html

email team feature

---

src/assets/app.css
src/users/loginView/loginView.tpl.html

Closes #178
There is now a bit of help text that lets users know which credentials to use when logging in.

Indicates which Login Credentials

---

server/db.js

Pretty simple PR. Review it @Mctalian, @bcbrennecke!
This will close #228.

timeModified now updates

---

src/ideas/ideasView/ideasView.spec.js
src/navigation/toolbar.spec.js

Fixed it @YashdalfTheGray @Mctalian

Fixed Console Log Issues

---

server/routes.js
src/ideas/ideaSvc/ideaSvc.js
src/ideas/ideaSvc/ideaSvc.spec.js
src/users/userSvc/userSvc.js
src/users/userSvc/userSvc.spec.js

Not much to say, changed our REST API mount point to `api/v1` instead of `/ideas` or `/users`, etc.
Reviewers (or mostly just look at it): @bcbrennecke, @monotkate, @alanlgirard

endpoints are now mounted under "/api/v1"

---

.bowerrc
README.md

I got the server up and running on Linux (with SSL).
This corrects something in the `.bowerrc` file and also documents all the crap I had to do to get everything running. It amazes me that TravisCI handles everything so well.
I was going to work out how to get mongo authentication going, but I'll do that somewhere else.

Linux Changes

---

src/assets/app.css
src/ideas/ideaInput/ideaInput.tpl.html
src/ideas/ideasView/ideasView.tpl.html

Increased the idea title character limit to 150 and fixed some over-flow/word wrapping issues
Closes issue  #254 
Simple review @YashdalfTheGray @Mctalian @monotkate @davethenipper

Increase Idea Title Character Limit to 150

---

generateData.js
src/ideas/ideaSvc/ideaSvc.mock.js
src/ideas/ideaSvc/ideaSvc.spec.js

This takes care of the first part of #265.
The existing data still needs to be updated.
Please check off when finished reviewing:

Replaced time properties with timeCreated

---

src/homeView/homeView.js
src/homeView/homeView.tpl.html

-Changed md-content tag to a div in homeview.tpl.html
-Changed www.innovate.com link to a #.
-Added space to the end of filler words to stop concatenation of words
Review me @YashdalfTheGray @Mctalian

Fixed errors @mctalian found this morning

---

src/index.html

I'm not waiting for approvals on this

Changed Rokstarter in tab title to Innovate

---

bower.json
package.json
server/ideas/ideaModel.js
server/routes.js
src/ideas/ideaInput/IdeaInputCtrl.js

Search fixes, lodash 4.1.0 and the ability to search ideas by comment authors

---

src/index.html

@alanlgirard, @bcbrennecke, @YashdalfTheGray, @davethenipper, @monotkate 
Reviewers

Fixes #284

---

server/routes.js
src/ideas/ideaInput/IdeaInputCtrl.js
src/ideas/ideaInput/ideaInput.tpl.html

This is kinda temporary since there's a bug and we need to discuss how events are going to be utilized in the future.
Closes #277 
@YashdalfTheGray, @davethenipper, @alanlgirard 
Reviewers

Disable events

---

src/ideas/ideasView/ideasView.tpl.html

Closes #289.  
Simple 1 word fix @monotkate @YashdalfTheGray @Mctalian @bcbrennecke

IE Idea Title Wrapping Fix

---

src/homeView/homeView.js
src/homeView/homeView.spec.js
src/homeView/homeView.tpl.html
src/index.html

I added a message that displays when someone opens the webpage in IE.  This only displays on the homepage.
Note: This is not our excuse to start ignoring IE compatibility while developing, it is strictly to save us if we miss something on a page.
Review me! @YashdalfTheGray @Mctalian @LongArmMcGee @davethenipper @monotkate @alanlgirard

Added message to display if IE is the browser being used

---

CONTRIBUTING.md

Updated contributing.md after the discussion this afternoon. 
@Mctalian

added some more details to contributing

---

features/mobile-user-menu.feature

@Mctalian, merge this to start working on your card

feature file for mobile login menu

---

src/ideas/ideaBrowseView/ideaBrowseView.js
src/ideas/ideasView/ideasView.js
src/index.html
src/navigation/sidenav.js
src/utilities/sseSvc.js
src/utilities/sseSvc.mock.js
src/utilities/sseSvc.spec.js

Addresses #309. Whether or not we want to close that out is another story (socket.io or WebSockets might be the official closure?), but this does buy us time.
**Problem**
Opening 2 tabs on Chrome would cause us to use up the 6 open connections that Chrome allows to a single server at a given time. This was caused because we were instantiating `SidenavCtrl` 3 times in `index.html`.
**Solution**
I removed both of the extra `SidenavCtrl` instantiations and slightly refactored to remove the "dependency" on that controller in one of the "extra" places. (I used a `ui-sref`instead of the `navTo` call).
Furthermore, I upgraded sseSvc to be closer to a pub/sub pattern. The server is doing the publishing, so we don't need to worry about that. But the `create` call was refactored to a `subscribe` …

Patch 309 and sseSvc refactor

---

src/ideas/addIdeaView/addIdeaView.js
src/ideas/addIdeaView/addIdeaView.spec.js
src/ideas/ideasView/ideasView.js
src/ideas/ideasView/ideasView.spec.js
src/learn/learn.js
src/learn/learn.spec.js
src/navigation/toolbar.js
src/users/userSvc/userSvc.js
src/users/userSvc/userSvc.spec.js

This PR enables tracking of all interactions, adding and deleting ideas, and even if people click on the Learn images to see the pictures closer.
No functionality is altered here with the Google Analytics stuff, and all of the code is just sending data using the Google Analytics API.
I changed the "Your credentials don't match the stored ones :(" toast to "Invalid Credentials :(" just in case people got scared that we were storing their stuff.

More Google Analytics (and changed failed login toast)
